; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2 on Thu Jan 31 2019 15:46:23 GMT+0100 (Midden-Europese standaardtijd)

