; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2 on Thu Jan 31 2019 15:46:23 GMT+0100 (Midden-Europese standaardtijd)
; Wait for set temperatures to be reached
M116 P0

