; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2 on Thu Jan 31 2019 15:46:22 GMT+0100 (Midden-Europese standaardtijd)
M561                ; clear any bed transform
M98 Pdeployprobe.g  ; deploy mechanical Z probe
G29                 ; probe the bed and enable compensation
M98 Pretractprobe.g ; retract mechanical Z probe


