; resume.g
; called before a print from SD card is resumed
;
; generated by RepRapFirmware Configuration Tool on Thu Sep 06 2018 21:21:12 GMT-0700 (Pacific Daylight Time)
G1 R1 X0 Y0 Z1 F6000 ; go to 5mm above position of the last print move
G1 R1 X0 Y0       ; go back to the last print move
M83                  ; relative extruder moves
G1 E4 F3600         ; extrude 10mm of filament