; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool on Thu Sep 06 2018 21:21:12 GMT-0700 (Pacific Daylight Time)
; Wait for set temperatures to be reached
M116 P0